#!/usr/bin/env bash
ls
set -ex
# Navigate to the directory containing setup.py
# cd /root/capsule/code/utils

# Build Cython extensions in place
# python setup.py build_ext --inplace

pwd
 
# python -u run_capsule.py --input ../data/iGluSnFR4f_dendrite_passiveDriftingGratings/743712_01 --output ../results/
# python -u run_capsule.py --input ../data/iGluSnFR_simulations_z_default/1 --output  ../results/

# Capture input and output from command-line arguments
input=$1
output=$2

echo "input=$1"
echo "output=$2"

# Run the Python script with the passed arguments
python -u run_capsule.py --input "$input" --output "$output" --ds_time 0