#!/usr/bin/env bash
ls
set -ex
# # Navigate to the directory containing setup.py
# cd /root/capsule/code/utils

# # Build Cython extensions in place
# python setup.py build_ext --inplace

# export JAX_TRACEBACK_FILTERING=off

# python -u run_capsule.py --input ../data/iGluSnFR-testing-Sim-Data-ReleaseSites_1/ --output ../scratch/testing/ #../results/

pwd

# python -u run_capsule.py --input ../data/iGluSnFR-Michael-testing --output ../results/

# python -u run_capsule.py --input ../data/iGluSnFR_simulations --output ../results/

# python -u run_capsule.py --input ../data/scan_00010_20240815_140228_adrian --output ../results/

# python -u run_capsule.py --input ../data/iGluSnFR-Michael-testing --output ../scratch/testing/


# Capture input and output from command-line arguments
input=$1
output=$2

echo "input=$1"
echo "output=$2"

# Run the Python script with the passed arguments
python -u run_capsule.py --input "$input" --output "$output" --ds_time 0